apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: build
on:
  workflow_dispatch:
    inputs:
      image-name:
        type: string
        required: true
        default: pyexamples
  workflow_call:
    inputs:
      image-name:
        type: string
        required: true
        default: pyexamples
jobs:
  build:
    steps:
      - uses: cloudbees-io/checkout@v2
        name: Get source code

      - name: Sign in to OCI registry
        uses: https://github.com/cloudbees-io/configure-oci-credentials@v1
        with:
          registry: https://index.docker.io/v1/
          username: ${{ secrets.OCI_USERNAME }}
          password: ${{ secrets.OCI_PASSWORD }}

      # Build image (tar file)
      - name: Build image
        uses: docker://gcr.io/kaniko-project/executor:v1.23.2-debug
        kind: build
        id: build-image
        run: |
          /kaniko/executor \
            --context "$CLOUDBEES_WORKSPACE" \
            --dockerfile Dockerfile \
            --no-push \
            --tar-path "image.tar" \
            --destination "${{ inputs.image-name }}:${{ cloudbees.scm.sha }}" \
            --digest-file "digest.txt"

      - name: Export Image Digest
        uses: docker://alpine:latest
        run: |
          DIGEST=$(cat "$CLOUDBEES_WORKSPACE/digest.txt")
          echo "IMAGE_DIGEST=$DIGEST" >> "$CLOUDBEES_OUTPUTS"

      # Scan it
      # - name: Scan with Snyk Container
      #   uses: cloudbees-io/snyk-scan-container@v1
      #   with:
      #     orgname: ${{ vars.SNYK_ORG }}
      #     token: ${{ secrets.SNYK_TOKEN }}
      #     image-location: "docker-archive:$CLOUDBEES_WORKSPACE/image.tar"
      #     image-tag: "${{ inputs.image-name }}:${{ cloudbees.scm.sha }}"
      # Upload to ASPM
      - id: upload-binary
        name: Upload binary using action
        uses: https://github.com/cloudbees-io/asset-chain-utils/upload-binary@v1
        with:
          file-path: "image.tar"
          file-type: BINARY_CONTAINER
      # Gate it
      # Push it
      - name: Push image to registry
        uses: docker://gcr.io/go-containerregistry/crane:debug
        run: |
          crane push "image.tar" "index.docker.io/${{ secrets.OCI_USERNAME }}/${{ inputs.image-name }}:${{ cloudbees.scm.sha }}"

      # Register build artifact
      - name: Register an artifact with the platform
        id: register
        uses: cloudbees-io/register-build-artifact@v2
        with:
          name: ${{ inputs.image-name }}
          url: docker.io/${{ secrets.OCI_USERNAME }}/${{ inputs.image-name }}:${{ cloudbees.scm.sha }}
          version: ${{ cloudbees.scm.sha }}
          digest: ${{ steps.build-image.outputs.IMAGE_DIGEST }}
