apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: build
on:
  workflow_dispatch:
  workflow_call:
jobs:
  build:
    steps:
      - uses: cloudbees-io/checkout@v1
        name: Get source code

      - name: Sign in to OCI registry
        uses: https://github.com/cloudbees-io/configure-oci-credentials@v1
        with:
          registry: https://index.docker.io/v1/
          username: ${{ secrets.OCI_USERNAME }}
          password: ${{ secrets.OCI_PASSWORD }}

      # Build image (tar file)
      - name: Build container image
        uses: docker://bitnami/kaniko:latest
        kind: build
        id: build-image
        run: |
          /kaniko/executor \
            --context "$CLOUDBEES_WORKSPACE" \
            --dockerfile Dockerfile \
            --no-push \
            --tar-path "$CLOUDBEES_WORKSPACE/image.tar" \
            --destination "pyexamples:${{ cloudbees.scm.sha }}"

      # Scan it
      # Upload to ASPM
      # Gate it
      # Push it

      # Register build artifact
